track_parcel:
  fields:
    tracking_code:
      required: true
      example: "CW000000000IT"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "CW000000000IT"
      selector:
        text:
